In [15]:
import pandas as pd
import json
import glob
import re

# Загрузка всех файлов
files = glob.glob('../../data/*/*_*_stats.json')
files
data = []

for f in files:
    with open(f, 'r') as file:
        stats = json.load(file)
        stats['file'] = f
        data.append(stats)

# Создание DataFrame
df = pd.DataFrame(data)

def extract_model_name(filepath):
    """
    Извлекает имя модели из пути к файлу
    Пример: '../../data/output/yolo_cuda_stats.json' -> 'yolo'
            '../../data/output/frcnn_onnx_cuda_stats.json' -> 'frcnn_onnx'
    """
    # Получаем имя файла без пути
    filename = filepath.split('/')[-1]
    # Убираем '_stats.json' и возможные суффиксы устройств
    model_name = filename.replace('_stats.json', '')
    # Убираем суффиксы _cuda, _cpu в конце
    model_name = re.sub(r'_(cuda|cpu)$', '', model_name)
    return model_name

# Применяем функцию
df['model_name'] = df['file'].apply(extract_model_name)

# Результат
print(df[['model_name', 'fps', 'mean']])

      model_name        fps         mean
0     frcnn_onnx        NaN    72.510763
1          frcnn        NaN    78.497550
2     frcnn_onnx   0.902383  1108.176705
3       yolo_v5s        NaN    49.747932
4           yolo  24.984750    40.024415
5          frcnn   0.699093  1430.424528
6  yolo_tensorRT        NaN    11.126633
7    yolo_tensor        NaN    16.294749
8           yolo   4.696172   212.939410
9       yolo_v5s        NaN     9.288099

In [16]:
df.sort_values('fps_model_inference', ascending=False)[['model_name', 'fps_model_inference', 'mean']].round(2)

      model_name  fps_model_inference     mean
9       yolo_v5s               107.66     9.29
6  yolo_tensorRT                89.87    11.13
7    yolo_tensor                61.37    16.29
3       yolo_v5s                20.10    49.75
0     frcnn_onnx                13.79    72.51
1          frcnn                12.74    78.50
2     frcnn_onnx                  NaN  1108.18
4           yolo                  NaN    40.02
5          frcnn                  NaN  1430.42
8           yolo                  NaN   212.94

In [14]:
df

,mean,median,std,min,max,fps,num_runs,p95,p99,file,fps_model_inference,model_name
0,101.341322,78.157137,123.965023,75.080776,779.899630,9.867643,31,91.244828,575.433862,../../data/output/frcnn_onnx_cuda_stats.json,NaN,frcnn_onnx
1,78.497550,77.703154,10.823227,74.275604,358.782194,NaN,705,82.522108,86.798530,../../data/output/frcnn_cuda_stats.json,12.739251,frcnn
2,1108.176705,1102.664764,33.118641,1060.807112,1194.405648,0.902383,14,1159.927272,1187.509973,../../data/output/frcnn_onnx_cpu_stats.json,NaN,frcnn_onnx
3,49.747932,49.715687,4.658524,42.692971,152.965042,NaN,705,53.505094,57.275542,../../data/output/yolo_v5s_cpu_stats.json,20.101338,yolo_v5s
4,40.024415,38.859728,18.614477,33.977487,526.768072,24.984750,705,44.457849,49.600124,../../data/output/yolo_cuda_stats.json,NaN,yolo
5,1430.424528,1420.880147,57.855795,1332.925220,1554.445384,0.699093,21,1516.607844,1546.877876,../../data/output/frcnn_cpu_stats.json,NaN,frcnn
6,11.126633,10.584004,2.799313,8.637453,60.101213,NaN,705,14.296533,18.862084,../../data/output/yolo_tensorRT_cuda_stats.json,89.874451,yolo_tensorRT
7,16.294749,16.339273,3.994287,11.288421,88.293258,NaN,705,20.835831,22.268982,../../data/output/yolo_tensor_cuda_stats.json,61.369462,yolo_tensor
8,212.939410,209.057424,27.027255,181.187113,877.175881,4.696172,705,233.748204,244.012493,../../data/output/yolo_cpu_stats.json,NaN,yolo
9,9.288099,8.622829,4.212625,6.313886,99.098213,NaN,705,13.188680,19.570192,../../data/output/yolo_v5s_cuda_stats.json,107.664656,yolo_v5s